// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddManyToAlbum(arg1, arg2) {
  return window['go']['main']['App']['AddManyToAlbum'](arg1, arg2);
}

export function AddManyToSafe(arg1) {
  return window['go']['main']['App']['AddManyToSafe'](arg1);
}

export function AddToAlbum(arg1, arg2) {
  return window['go']['main']['App']['AddToAlbum'](arg1, arg2);
}

export function AddToSafe(arg1) {
  return window['go']['main']['App']['AddToSafe'](arg1);
}

export function AlbumCount(arg1) {
  return window['go']['main']['App']['AlbumCount'](arg1);
}

export function AlbumItems(arg1, arg2, arg3) {
  return window['go']['main']['App']['AlbumItems'](arg1, arg2, arg3);
}

export function CopyFilesToClipboard(arg1) {
  return window['go']['main']['App']['CopyFilesToClipboard'](arg1);
}

export function CopyPathsToClipboard(arg1) {
  return window['go']['main']['App']['CopyPathsToClipboard'](arg1);
}

export function CreateAlbum(arg1) {
  return window['go']['main']['App']['CreateAlbum'](arg1);
}

export function CreateSafe(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSafe'](arg1, arg2, arg3);
}

export function CreateSmartAlbum(arg1, arg2) {
  return window['go']['main']['App']['CreateSmartAlbum'](arg1, arg2);
}

export function DeleteAlbum(arg1) {
  return window['go']['main']['App']['DeleteAlbum'](arg1);
}

export function DeleteFiles(arg1) {
  return window['go']['main']['App']['DeleteFiles'](arg1);
}

export function DeleteSafe() {
  return window['go']['main']['App']['DeleteSafe']();
}

export function DeleteSmartAlbum(arg1) {
  return window['go']['main']['App']['DeleteSmartAlbum'](arg1);
}

export function Duplicates() {
  return window['go']['main']['App']['Duplicates']();
}

export function Favorites(arg1, arg2, arg3) {
  return window['go']['main']['App']['Favorites'](arg1, arg2, arg3);
}

export function FavoritesCount(arg1) {
  return window['go']['main']['App']['FavoritesCount'](arg1);
}

export function GeoItems(arg1, arg2) {
  return window['go']['main']['App']['GeoItems'](arg1, arg2);
}

export function GetProgress() {
  return window['go']['main']['App']['GetProgress']();
}

export function GetSectionItems(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetSectionItems'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSections(arg1) {
  return window['go']['main']['App']['GetSections'](arg1);
}

export function IsSafeUnlocked() {
  return window['go']['main']['App']['IsSafeUnlocked']();
}

export function ListAlbums() {
  return window['go']['main']['App']['ListAlbums']();
}

export function ListSmartAlbums() {
  return window['go']['main']['App']['ListSmartAlbums']();
}

export function LockSafe() {
  return window['go']['main']['App']['LockSafe']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function RatedCount(arg1, arg2) {
  return window['go']['main']['App']['RatedCount'](arg1, arg2);
}

export function RatedItems(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RatedItems'](arg1, arg2, arg3, arg4);
}

export function RemoveFromAlbum(arg1, arg2) {
  return window['go']['main']['App']['RemoveFromAlbum'](arg1, arg2);
}

export function RemoveFromSafe(arg1) {
  return window['go']['main']['App']['RemoveFromSafe'](arg1);
}

export function RenameAlbum(arg1, arg2) {
  return window['go']['main']['App']['RenameAlbum'](arg1, arg2);
}

export function RevealInFileManager(arg1) {
  return window['go']['main']['App']['RevealInFileManager'](arg1);
}

export function SafeCount() {
  return window['go']['main']['App']['SafeCount']();
}

export function SafeInfo() {
  return window['go']['main']['App']['SafeInfo']();
}

export function SafeItems(arg1, arg2) {
  return window['go']['main']['App']['SafeItems'](arg1, arg2);
}

export function Search(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3, arg4);
}

export function SetRating(arg1, arg2) {
  return window['go']['main']['App']['SetRating'](arg1, arg2);
}

export function SmartAlbumCount(arg1) {
  return window['go']['main']['App']['SmartAlbumCount'](arg1);
}

export function SmartAlbumItems(arg1, arg2, arg3) {
  return window['go']['main']['App']['SmartAlbumItems'](arg1, arg2, arg3);
}

export function Stats() {
  return window['go']['main']['App']['Stats']();
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function TotalCount(arg1, arg2) {
  return window['go']['main']['App']['TotalCount'](arg1, arg2);
}

export function UnlockSafe(arg1) {
  return window['go']['main']['App']['UnlockSafe'](arg1);
}
