// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddManyToAlbum(arg1:number,arg2:Array<string>):Promise<void>;

export function AddManyToSafe(arg1:Array<string>):Promise<void>;

export function AddToAlbum(arg1:number,arg2:string):Promise<void>;

export function AddToSafe(arg1:string):Promise<void>;

export function AlbumCount(arg1:number):Promise<number>;

export function AlbumItems(arg1:number,arg2:number,arg3:number):Promise<Array<main.Media>>;

export function CopyFilesToClipboard(arg1:Array<string>):Promise<void>;

export function CopyPathsToClipboard(arg1:Array<string>):Promise<void>;

export function CreateAlbum(arg1:string):Promise<number>;

export function CreateSafe(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateSmartAlbum(arg1:string,arg2:string):Promise<number>;

export function DeleteAlbum(arg1:number):Promise<void>;

export function DeleteFiles(arg1:Array<string>):Promise<void>;

export function DeleteSafe():Promise<void>;

export function DeleteSmartAlbum(arg1:number):Promise<void>;

export function Duplicates():Promise<Array<main.DuplicateGroup>>;

export function Favorites(arg1:string,arg2:number,arg3:number):Promise<Array<main.Media>>;

export function FavoritesCount(arg1:string):Promise<number>;

export function GeoItems(arg1:number,arg2:number):Promise<Array<main.Media>>;

export function GetProgress():Promise<main.ScanProgress>;

export function GetSectionItems(arg1:number,arg2:number,arg3:string,arg4:number,arg5:number):Promise<Array<main.Media>>;

export function GetSections(arg1:string):Promise<Array<main.Section>>;

export function IsSafeUnlocked():Promise<boolean>;

export function ListAlbums():Promise<Array<main.Album>>;

export function ListSmartAlbums():Promise<Array<main.SmartAlbum>>;

export function LockSafe():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function RatedCount(arg1:number,arg2:string):Promise<number>;

export function RatedItems(arg1:number,arg2:string,arg3:number,arg4:number):Promise<Array<main.Media>>;

export function RemoveFromAlbum(arg1:number,arg2:string):Promise<void>;

export function RemoveFromSafe(arg1:string):Promise<void>;

export function RenameAlbum(arg1:number,arg2:string):Promise<void>;

export function RevealInFileManager(arg1:string):Promise<void>;

export function RunOCR(arg1:string):Promise<string>;

export function SafeCount():Promise<number>;

export function SafeInfo():Promise<main.SafeInfo>;

export function SafeItems(arg1:number,arg2:number):Promise<Array<main.Media>>;

export function Search(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<main.Media>>;

export function SetRating(arg1:string,arg2:number):Promise<void>;

export function SmartAlbumCount(arg1:string):Promise<number>;

export function SmartAlbumItems(arg1:string,arg2:number,arg3:number):Promise<Array<main.Media>>;

export function Stats():Promise<Record<string, number>>;

export function ToggleFavorite(arg1:string):Promise<boolean>;

export function TotalCount(arg1:string,arg2:string):Promise<number>;

export function UnlockSafe(arg1:string):Promise<boolean>;
